### ISSUE TITLE
Table View

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/SpreadSheetTool#1]
As a Squeak-User, I want to be able to view tables, in order to organize 2D data.

Acceptance Criteria:
- [x] I can open a Table Morph
- [x] The table contains 5 rows and 5 columns

Estimated effort: 5

**Comment by LeonMatthes** [comment]
Please make the code to open simpler:
e.g. `SSSheetModel open`

**Comment by LinqLover** [comment]
(Back to the roots:) Most time I use the sheet I, the first thing I do is reducing its size as I find a bigger cell extent more comfortable. @MrModder Would you agree us to lower the default sheet size, which is currently fixed to 5×5 by an acceptance criterium above?

**Comment by LeonMatthes** [comment]
> (Back to the roots:) Most time I use the sheet I, the first thing I do is reducing its size as I find a bigger cell extent more comfortable. @MrModder Would you agree us to lower the default sheet size, which is currently fixed to 5×5 by an acceptance criterium above?

Yes of course, no problem.
The 5x5 values were just examples, change them however you see fit.
