### ISSUE TITLE
Save/Load sheet in image

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/SpreadSheetTool#14]
As a SqueakSheet user who wants to minimize the number of open windows, I want to be able to save my progress in the image, in order to be able to close the SqueakSheet window and not loose the progress.

Acceptance criteria:
- [x] A button exists to save the sheet in the image
- [x] A button exists to load a sheet from the image
- [x] When I save the sheet, I am asked for a name for the save
- [x] When a sheet is loaded, SqueakSheet presents me with a list of all available saves
- [x] When I edit a SqueakSheet that was previously saved, the save is not changed

**Comment by LinqLover** [comment]
Estimated effort: 21

**Comment by LinqLover** [comment]
New estimated effort: 8
