### ISSUE TITLE
Warning/error message for bad sheet dimension inputs

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/SpreadSheetTool#21]
As a Squeak-Luser, IWLT get warning/error messages when I enter an inappropriate sheet size, in order to prevent that my GUI hangs up or a debugger window opens.

# Acceptance criteria
- [x] When I enter an invalid number (e. g. `1.5`, `-42`, `0`, `foo` or ` `) into the row or column count input field, an error message is shown that explains the problem. The old size is kept then and no debugger window appears. The last typed number is not deleted nor accepted.
- [x] When I enter an inappropriate large number that would make Squeak freeze for some time, I am displayed a warning message that explains the limits of Squeak and lets me choice whether I would like to continue.
  - [x] If I choose to continue, the tool tries to apply the entered size.
  - [x] If I decline, the old size is kept.

**Comment by LinqLover** [comment]
Estimated effort: 5

**Comment by LinqLover** [comment]
Other invalid instances: `5a`
Question: Is it ok to accept this input as '5' as this is the usual behavior of Squeak? @MrModder

**Comment by LeonMatthes** [comment]
> Other invalid instances: `5a`
> Question: Is it ok to accept this input as '5' as this is the usual behavior of Squeak? @MrModder

For me this really does not matter, do whatever is easiest for you.
