### ISSUE TITLE
Delete saved sheets

### ISSUE THREAD

**Issue by AndreaNathansen** [hpi-swa-teaching/SpreadSheetTool#27]
As a user who frequently saves sheets in the image I want to be able to delete saved sheets from the image.

Acceptance criteria:
- [x] There is a button with a label to delete sheets.
- [x] When I click the button, I get a list of the names of all saved sheets
- [x] When I select a sheet from the list, I am asked if I really want to delete it (dialog should include the name again)
- [x] When I confirm, the sheet doesn't appear in the list of the saved sheets anymore

**Comment by LinqLover** [comment]
Proposal: We could allow the user to select multiple sheets from the sheet once.

Using `#chooseMultipleFrom:values:` instead of `chooseFrom:values:`, this should not make a big difference for implementation.
