### ISSUE TITLE
Simple cross-referencing formulas

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/SpreadSheetTool#39]
As an enthusiastic Squeak User, IWLT be able to refer from the formula of one cell to the value of another cell in my sheet, in order to describe dependencies by calculations. The protocol should be very convenient so that I do not need to look up any implementation source.

# Acceptance criteria
- [ ] When I accept a formula into a cell, `self` understands the following messages:
   - [ ] `#rowHeader`, `#columnHeader` - return the values of the relevant header cell
   - [ ] `#atRow:atColumn:`, `#atColumn:atRow:` - return the value of the relevant cell.
      The arguments for row and column must be the indices starting with 1.
   - [ ] `#at:` - a shorthand for the above variant, where the argument must be a point, of which x goes column and y goes row.
   - [ ] `#left`, `#right`, `#above`, `#below` - returns the relative cell next to the current cell
   - [ ] `#leftBy:`, `#rightBy:`, `#aboveBy:`, `#belowBy:` - returns the relative cell, which is as many cells distant next to the current cell as the integer argument specifies. `self left: n negated` should equal `self right: n` etc. `0` is not a valid argument.
   - [ ] `#leftBy:aboveBy:`, `#leftBy:belowBy:`, `#rightBy:aboveBy:`, `#rightBy:belowBy:`, `#aboveBy:leftBy:`, `#aboveBy:rightBy:`, `#belowBy:leftBy:`, `#belowBy:rightBy:` - a composite of the messages above
- [ ] If the formula is somehow invalid (e. g. by sending a message not understood, an invalid argument to any of the above methods, or something other), an error/debugger window opens
- [ ] If I reference the contents of another cell, its value is NOT recomputed

**Comment by LeonMatthes** [comment]
Estimated effort: 8
