### ISSUE TITLE
Bug: Saving a sheet with an unsaved formula makes the formula uncomputable

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/SpreadSheetTool#42]
Scenario:
- Save a formula into a cell
- Edit the formula, but do not accept the changes
- Save the sheet into image*
- Reopen the sheet:

Now, the formula is displayed no matter if it has focus or not.

Workaround: Reedit the formula cell again and accept.

*We should discuss whether this should be possible in the current situation in any way.

**Comment by LinqLover** [comment]
Discussion postponed after implementation #48.

**Comment by LeonMatthes** [comment]
This is not an issue, because it reflects the current edit state when saving the sheet, I would consider this a feature
