### ISSUE TITLE
Cross Referencing Formulas: Enhance protocol (1)

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/SpreadSheetTool#45]
As an enthusiastic Squeak User keen on using formulas in SqueakSheet, IWLT have an even more convenient formula protocol. (1)

# Acceptance criteria
- [x] Add `#leftAbove`, `#aboveLeft`, `#rightAbove`, ... (should be 8 at all) as a shorthand for `self leftBy: 1 aboveBy: 1` etc.
- [x] Add `#rowHeaderAt:` and `#columnHeaderAt:` that return the content of the _n_-th header (where _n_ is the numeric argument, starting at 1)
- [x] Treat row/column headers as cells with index 0: `self atRow: 0 atColumn: 1` should equal `self rowHeaderAt: 1` and so on. Should also work for `#above`, `#left` etc.
- [x] When I use `self value` in a formula, use the last computed value instead of producing an infinity loop.

**Comment by georgt99** [comment]
Estimated: 3
