### ISSUE TITLE
Resizeable Tables

### ISSUE THREAD

**Issue by Scretch9** [hpi-swa-teaching/SpreadSheetTool#5]
As someone who wants to organize 2D data, I want to be able to **resize** tables, in order to be able to fit the table view to my needs.

Acceptance Criteria:
- [x] The SpreadSheetTool contains two Text fields
  * One is labeled: columns
  * One is labeled: rows
- [x] When I enter a number in the columns text field and save, the column count is changed.
- [x] The same goes for rows
- [x] The data in cells that are not removed does not disappear
- [x] When the Tool is first opened, the columns and rows fields are prefilled with the number of columns and rows

Estimated effort (25.4.19): 8
Estimated effort: 5

**Comment by LinqLover** [comment]
**Estimated effort for UI:** _fib([fib^-1(3)+fib^-1(5)]/2) = 3.89905516 - 0.0512944783 i_ ≈ **4**

(Estimated with @Scretch9)
