### ISSUE TITLE
multiple statement formulas

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/SpreadSheetTool#61]
Due to the used syntax, it is currently not possible to enter multiple statements. This should be changed.

Open question: How should the syntax be changed?

**Comment by LinqLover** [comment]
Issues with any non-standard syntax are:
1. The syntax must be parsed
2. When the formula was edited in a SyntaxError window, it must be transformed backwards
3. Normal PrintIt & Co. won't work, even on formula without cross-references

If we decide to specialize the [common syntax](https://gist.github.com/sin3141592/602700) by changing the following rule:
```ebnf
61. ExecutableCode = "^", [LocalVariableDeclarationList], [{Statement, OptionalWhitespace, "."}, FinalStatement, ["."]
```
then point 1. and 2. will be trivial (adding respective removing the first `^`). For 3., we will definitively need to implement #54, as the standard Compiler would not understand our syntax.

Some implementation notes closely regarding to #54 (spiked a bit):
- The relevant logic is located in `TextEditor>>#evaluateSelectionAndDo:`
- We probably would need to "only" provide `#evaluateExpression:` in our cell model

**Comment by LinqLover** [comment]
By now, you are able to enter multi-statement formulae by choosing a different model and pressing the getter button. Supporting such kind of formulae in the default hybrid formula models would be likely to break with their concept of simplicity.
