### ISSUE TITLE
Access object model

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/SpreadSheetTool#64]
As a smalltalk programmer, I want to be able to map certain object properties to a cell, in order to easier inspect my Objects.

**Acceptance criteria**
- [x] I want to be able to select a new kind of model which can access object properties
- [x] When selected, it allows me to choose 2 formulas, one to get and one to set the value
- [x] The model continuously monitors the value provided by the get formula
- [x] When entering a new value into the sheet, it gets evaluated and then saved in the target via the set formula

**Comment by LeonMatthes** [comment]
Estimated effort: 13

**Comment by LinqLover** [comment]
**Implementation note:** We could put this behavior into UniversalCellModel and sync the changes between the formula interface and the contained model. When the formula value changes, we can call #contents: on the model, and when the model's contents changes, we can call the set formula. For detecting the change, we can use a timer as well as the observer protocol.

**Comment by LinqLover** [comment]
**Updated Acceptance criteria**
- [ ] Each model has a formula button
- [ ] When clicked, it asks me for 2 formulas, one to get and one to set the value
- [ ] The model continuously monitors the value provided by the get formula
- [ ] If the provided get value changes, the #object: setter on the current model is called
- [ ] When the #object getter of the current model changes, its value is saved in the target via the set formula

**Comment by LinqLover** [comment]
@MrModder Did you accept #63, #45 and and #64? There are no ticks at all!
