### ISSUE TITLE
Updated needed: 'SSSheetTool exampleInspectingAMorph'

### ISSUE THREAD

**Issue by hhzl** [hpi-swa-teaching/SpreadSheetTool#72]
Great to see a tool for representing Squeak data in table format!

The example which shows how to inspect a morph refers to objects which are no longer there. 
- SSBooleanHolder
- SSColorPicker

Which are the replacements for these objects?

This is in Image
.../Squeak5.3-19435-64bit-All-in-One.app/Contents/Resources/Squeak5.3-19435-64bit.image
Squeak5.3
latest update: #19452
Image format 68021 (64 bit)

![SqueakSpreadSheetTool_exampleInspectingAMorph_needs_to_be_updated_2020-10-23](https://user-images.githubusercontent.com/1112023/96995191-54732800-151d-11eb-9f8b-241683ecf193.png)

**Comment by LinqLover** [comment]
Hey hhzl, thanks for reaching out! You're right, there was a configuration error in the baseline so if you used the recommended way to install the package these example models were missing. I'm pushing a fix right now.

**Comment by LinqLover** [comment]
You should now be able to load the fix by evaluating this in a workspace:

```smalltalk
Metacello new
	baseline: 'SpreadSheetTool';
	repository: 'github://hpi-swa-teaching/SpreadSheetTool:master/packages';
	load
```

If you have any further questions, please let me know! :-)
