### ISSUE TITLE
SSUniversalCellModel>>doesNotUnderstand: #world

### ISSUE THREAD

**Issue by hhzl** [hpi-swa-teaching/SpreadSheetTool#73]
When leaving a project with the spreadsheet open in it I get the error message
```
     SSUniversalCellModel>>doesNotUnderstand: #world
```

A possible fix  is to put the method #world in the 'accessing' category of SSUniversalCellModel with the following implementation

```
world

^ Project current world
```

After this fix it is possible to go to another project (for example 'previous project')

**Comment by LinqLover** [comment]
Thanks for reporting! I could not reproduce the bug but now it should be fixed. Could you maybe confirm that the issue does no longer occur? See https://github.com/hpi-swa-teaching/SpreadSheetTool/issues/72#issuecomment-715583548 on how to update SqueakSheet. :-)

**Comment by hhzl** [comment]
Thank you. It works fine now after the update in the master branch. 
Tested in Squeak 5.3 release with:
```
Metacello new
	baseline: 'SpreadSheetTool';
	repository: 'github://hpi-swa-teaching/SpreadSheetTool:master/packages';
	load
```
(not tested with alpha release)
